dist: trusty
sudo: true
language: python
cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=1.7 PG=9.2
  - DJANGO=1.7 PG=9.3
  - DJANGO=1.7 PG=9.4
  - DJANGO=1.7 PG=9.5
  - DJANGO=1.7 PG=9.6
  - DJANGO=1.8 PG=9.2
  - DJANGO=1.8 PG=9.3
  - DJANGO=1.8 PG=9.4
  - DJANGO=1.8 PG=9.5
  - DJANGO=1.8 PG=9.6
  - DJANGO=1.9 PG=9.2
  - DJANGO=1.9 PG=9.3
  - DJANGO=1.9 PG=9.4
  - DJANGO=1.9 PG=9.5
  - DJANGO=1.9 PG=9.6
  - DJANGO=1.10 PG=9.2
  - DJANGO=1.11 PG=9.3
  - DJANGO=1.11 PG=9.4
  - DJANGO=1.11 PG=9.5
  - DJANGO=1.11 PG=9.6

matrix:
  exclude:
  # Django 1.9+ doesn't support python 3.3
  - python: 3.3
    env: DJANGO=1.9
  - python: 3.3
    env: DJANGO=1.10
  - python: 3.3
    env: DJANGO=1.11

  # Django 1.7 doesn't support python 3.5+
  - python: 3.5
    env: DJANGO=1.7
  - python: 3.6
    env: DJANGO=1.7

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO
  - python setup.py -q install
  - add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main"
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - apt-get update
  - apt-get install postgresql-$PG postgresql-contrib-$PG -y --no-install-recommends
before_script:
  - psql -c 'CREATE ROLE test;' -U postgres
  - psql -c 'ALTER ROLE test WITH SUPERUSER;' -U postgres
  - psql -c 'ALTER ROLE test WITH LOGIN;' -U postgres
  - psql -c "ALTER ROLE test PASSWORD 'test';" -U postgres
  - psql -c 'CREATE DATABASE test OWNER test;' -U postgres
script:
  python runtests.py
